name: CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FUNCTION_NAME: chloe_digital_universal_analytics
  REGION: us-central1
  QUEUE_ID: universal-analytics

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --entry-point=main
          --region=${{ env.REGION }}
          --timeout=530
          --project=${{ secrets.PROJECT_ID }}
          --memory=4096MB
          --runtime=python39
          --trigger-http
          --service-account=${{ secrets.GCP_SA }}
          --set-env-vars=CLIENT_ID=${{ secrets.CLIENT_ID }},CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }},PROJECT_ID=${{ secrets.PROJECT_ID }},QUEUE_ID=${{ env.QUEUE_ID }},REGION=${{ env.REGION }},FUNCTION_NAME=${{ env.FUNCTION_NAME }},GCP_SA=${{ secrets.GCP_SA }}
